routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('questions', 'QuestionsController')->except('show');
Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::resource('questions.answers', 'AnswersController')->except(['create','index','show']);
Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoriteController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoriteController@destroy')->name('questions.unfavorite');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = ['title','body'];
            
    public function user()
    {
        
        return $this->belongsTo(User ::class);
        
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }
    public function getUrlAttribute()
    {
        return route('questions.show',$this->slug);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        if ($this->answers_count >0) {
            if ($this->best_answer_id) {
                return "answered-accepted";
            }
            return "answered";
        }
        return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function acceptBestAnswer(Answer $answer)
    {
        # code...
        $this->best_answer_id= $answer->id;
        $this->save();
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimeStamps();
    }

    public function isFavorited()
    {
        # code...
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }

    public function getFavoritesCount()
    {
        # code...
        return $this->favorites->count();
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Requests\AskQuestionRequest;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except'=> ['index','show']]);
    }
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $questions = Question::with('user')->latest()->paginate(5);
        return view('questions.index', compact('questions'));
        
    }
    
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        $question = new Question();
        return view('questions.create', compact('question'));
    }
    
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(AskQuestionRequest $request)
    {
        /**
        * untuk mengambil value dari input bisa pakai ini:
        * 1). $request->user()->question()->create($request->only('title','body'));
        * untuk mengambil value dari atribut input tertentu. 
        * untuk contoh, value yang terambil dari input title dan input body
        * 
        * 2). $request->user()->question()->create($request->all());
        * $request akan mengambil semua atribut input yang ada di form input
        */
        $request->user()->questions()->create($request->all());
        
        return redirect()->route('questions.index')->with('success', 'Your question has been submitted');
    }
    
    /**
    * Display the specified resource.
    *
    * @param  \App\Question  $question
    * @return \Illuminate\Http\Response
    */
    public function show(Question $question)
    {
        //dd($question->body);
        $question->increment('views');
        return view('questions.show', compact('question'));
    }
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Question  $question
    * @return \Illuminate\Http\Response
    */
    public function edit(Question $question)
    {
        /*if (\Gate::denies('update-question', $question)) {
            abort(403, 'Access Denied');    
        }*/

        $this->authorize('update', $question);
        
        return view('questions.edit', compact('question'));    
        
        
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Question  $question
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Question $question)
    {
        $this->authorize('update', $question);
        $question->update($request->all());
        return redirect('/questions')->with('success','Your question has been updated.');
    }
    
    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Question  $question
    * @return \Illuminate\Http\Response
    */
    public function destroy(Question $question)
    {
        /*if (\Gate::denies('delete-question', $question)) {
            abort(403, 'Access Denied');    
        }*/
        $this->authorize('delete', $question);
        $question->delete();
        
        return redirect('/questions')->with('success','Your question has been deleted.');
    }
}

resources/views/questions/_form.blade.php
@csrf
<div class="form-group">
    <label for="title">Question</label>
    <input type="text" name="title" value="{{old('title', $question->title)}} " class="form-control {{$errors->has('title')  ? 'is-invalid': ''}}">
    
    @if ($errors->has('title'))
    <div class="invalid-feedback">
        <strong>{{$errors->first('title')}} </strong>
    </div> 
    @endif
    
</div>
<div class="form-group">
    <label for="body">Explain your question</label>
    <textarea name="body" id="body" cols="30" rows="10" class="form-control {{$errors->has('body')  ? 'is-invalid': ''}} ">{{old('body', $question->body)}} </textarea>    
    @if ($errors->has('body'))
    <div class="invalid-feedback">
        <strong>{{$errors->first('body')}} </strong>
    </div> 
    @endif
</div>
<div class="form-group">
    <button type="submit" class="btn btn-outline-primary btn-lg">{{$buttonText}} </button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Ask Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back to all Question</a>
                        </div>
                    </div>
                    
                </div>
                
                <div class="card-body">
                    <form action="{{route('questions.store')}} " method="post">
                        @include('questions._form', ['buttonText'=>'Ask Question'])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Ask Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back to all Question</a>
                        </div>
                    </div>
                    
                </div>
                
                <div class="card-body">
                    <form action="{{route('questions.update', $question->id)}} " method="post">
                        {{ method_field('put')}}
                        @include('questions._form', ['buttonText'=>'Update Question'])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>All Questions</h2>
                        <div class="ml-auto">
                            <a href="{{route('questions.create')}}" class="btn btn-outline-secondary">Ask Question</a>
                        </div>
                    </div>
                    
                </div>
                
                <div class="card-body">
                    @include('layouts._messages')
                    @foreach ($questions as $question)
                    <div class="media">
                        <div class="d-flex flex-column counters">
                            <div class="vote">
                                <strong>{{$question->votes}} </strong> {{str_plural('vote',$question->votes)}}
                            </div>
                            <div class="status {{$question->status}}">
                                <strong>{{$question->answers_count}} </strong> {{str_plural('answer',$question->answers_count)}}
                            </div>
                            <div class="view">
                                {{$question->views." ".str_plural('view',$question->views)}}
                            </div>
                        </div>
                        <div class="media-body">
                            <div class="d-flex align-items-center">
                                <h3 class="mt-0"><a href="{{$question->url}} ">{{$question->title}}</a>  </h3>
                                <div class="ml-auto">
                                    @can ('update',$question)
                                    <a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>   
                                    @endcan
                                    @can('delete',$question)
                                    <form class="form-delete" action="{{route('questions.destroy', $question->id)}} " method="post">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</button>
                                    </form>
                                    @endcan 
                                    
                                </div>
                            </div>
                            
                            <p class="lead">
                                Asked by 
                                <a href="{{$question->user->url}} ">{{$question->user->name}} </a>
                                <small class="text-muted">{{$question->created_date}} </small>
                            </p>
                            {{str_limit($question->body,250)}}
                        </div>
                    </div>
                    <hr>
                    @endforeach
                    
                    {{$questions->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <div class="d-flex align-items-center">
                            <h1>{{$question->title}} </h1>
                            <div class="ml-auto">
                                <a href="{{route('questions.index')}}" class="btn btn-outline-secondary">Back to all Question</a>
                            </div>
                        </div>
                        <hr>
                    </div>
                    
                    <div class="media">
                        <div class="d-flex flex-column vote-controls">
                            <a title="This question is useful" class="vote-up" >
                                <i class="fa fa-caret-up fa-3x"></i>
                            </a>
                            <span class="votes-count">1234</span>
                            <a title="This question is not useful" class="vote-down off" >
                                <i class="fa fa-caret-down fa-3x"></i>
                            </a>
                            <a title="Click to mark as favorite question (Click again to undo)" class="favorite {{ Auth::guest() ? 'off':($question->is_favorited ?'favorited':'')}} "
                                onclick="event.preventDefault(); document.getElementById('favorite-question-{{$question->id}}').submit(); ">
                                <i class="fa fa-star fa-2x"></i>
                                <span class="favorite-count">{{$question->favorites_count}} </span>
                            </a>
                            <form action="/questions/{{$question->id}}/favorites " method="post" style="display:none;" 
                                id="favorite-question-{{$question->id}}">
                                @csrf
                                @if ($question->is_favorited)
                                    @method('DELETE')
                                @endif
                            </form>
                        </div>
                        <div class="media-body">
                            {!!$question->body_html!!}
                            <div class="float-right">
                                <span class="text-muted">Answered {{$question->created_date}} </span>
                                <div class="media mt-2">
                                    <a href="{{$question->user->url}} " class="pr-2">
                                        <img src="{{$question->user->avatar}} " alt="">
                                    </a>
                                    <div class="media-body mt-1">
                                        <a href="{{$question->user->url}} ">{{$question->user->name}} </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('answers._index',[
        'answers' => $question->answers,
        'answersCount' => $question->answers_count
    ])
    @include('answers._create')
</div>
@endsection